model_path: /mnt/f/BoostCamp/service/Boostcamp-AI-Tech-Product-Serving/part2/02-streamlit/model.pt
home_path: /mnt/f/BoostCamp/service/Boostcamp-AI-Tech-Product-Serving/part2/02-streamlit
model_name: snunlp/KR-ELECTRA-discriminator